import {
    FaReact,
    FaJs,
    FaHtml5,
    FaCss3Alt,
    FaNodeJs,
    FaPython,
    FaAws,
    FaDocker,
    FaLinux,
    FaJava,
} from "react-icons/fa";

import {
    SiMongodb,
    SiExpress,
    SiTypescript,
    SiPandas,
    SiApachespark,
    SiTailwindcss,
    SiRedux,
    SiBootstrap,
    SiMui,
    SiNextdotjs,
    SiVite,
    SiPostman,
    SiGraphql,
    SiSocketdotio,
    SiDjango,
    SiFlask,
    SiMysql,
    SiPostgresql,
    SiFirebase,
    SiRedis,
    SiSupabase,
    SiNumpy,
    SiScikitlearn,
    SiTensorflow,
    SiPytorch,
    SiJest,
    SiMocha,
    SiCypress,
    SiJenkins,
    SiGit,
    SiGithub,
    SiGitlab,
    SiVercel,
    SiNetlify,
    SiCircleci,
    SiGithubactions,
    SiNpm,
    SiYarn,
    SiWebpack,
    SiBabel,
    SiEslint,
    SiPrettier,
} from "react-icons/si";

import { GiArtificialIntelligence } from "react-icons/gi";

export const skillsWithIcons = {
    React: FaReact,
    JavaScript: FaJs,
    HTML: FaHtml5,
    CSS: FaCss3Alt,
    Node: FaNodeJs,
    Java: FaJava,
    "Node.js": FaNodeJs,
    Express: SiExpress,
    MongoDB: SiMongodb,
    Python: FaPython,
    Pandas: SiPandas,
    "Machine Learning": GiArtificialIntelligence,
    Statistics: SiApachespark,
    AWS: FaAws,
    Docker: FaDocker,
    "CI/CD": SiJenkins,
    Linux: FaLinux,
    TypeScript: SiTypescript,
    TailwindCSS: SiTailwindcss,
    Redux: SiRedux,
    Bootstrap: SiBootstrap,
    MaterialUI: SiMui,
    NextJS: SiNextdotjs,
    Vite: SiVite,
    Postman: SiPostman,
    GraphQL: SiGraphql,
    SocketIO: SiSocketdotio,
    Django: SiDjango,
    Flask: SiFlask,
    MySQL: SiMysql,
    PostgreSQL: SiPostgresql,
    Firebase: SiFirebase,
    Redis: SiRedis,
    Supabase: SiSupabase,
    NumPy: SiNumpy,
    ScikitLearn: SiScikitlearn,
    TensorFlow: SiTensorflow,
    PyTorch: SiPytorch,
    Jest: SiJest,
    Mocha: SiMocha,
    Cypress: SiCypress,
    Git: SiGit,
    GitHub: SiGithub,
    GitLab: SiGitlab,
    Vercel: SiVercel,
    Netlify: SiNetlify,
    CircleCI: SiCircleci,
    GitHubActions: SiGithubactions,
    NPM: SiNpm,
    Yarn: SiYarn,
    Webpack: SiWebpack,
    Babel: SiBabel,
    ESLint: SiEslint,
    Prettier: SiPrettier,
};
