import { Link } from "react-router-dom";
import { FaRobot, FaHistory, FaLightbulb, FaQuoteLeft } from "react-icons/fa";
import { motion } from "framer-motion";
import { toast } from "react-hot-toast";

const features = [
    {
        icon: <FaRobot size={32} className="text-teal-600" />,
        title: "AI-Powered Questions",
        desc: "Get tailored interview questions generated by advanced AI.",
    },
    {
        icon: <FaLightbulb size={32} className="text-teal-600" />,
        title: "Instant Feedback",
        desc: "Receive real-time feedback to improve your answers.",
    },
    {
        icon: <FaHistory size={32} className="text-teal-600" />,
        title: "Track Progress",
        desc: "Review your interview history and monitor your growth.",
    },
];

const testimonials = [
    {
        quote: "PrepAI helped me land my dream job! The AI questions felt just like the real thing.",
        name: "Amit S.",
    },
    {
        quote: "The instant feedback is a game changer. I improved so much in just a week.",
        name: "Priya K.",
    },
];

const faqs = [
    {
        q: "Is PrepAI free to use?",
        a: "Yes, you can start practicing interviews for free.",
    },
    {
        q: "How does the AI generate questions?",
        a: "Our AI analyzes your chosen topics and creates relevant, challenging questions.",
    },
];

const Home = () => {
    const handleSubmit = (e) => {
        e.preventDefault();
        toast.success("You're subscribed to updates!");
    };

    return (
        <div className="min-h-screen bg-gradient-to-b from-teal-50 to-white">
            {/* Hero Section */}
            <motion.section
                className="text-center py-16 px-4"
                initial={{ opacity: 0, y: 40 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.8 }}
            >
                <h1 className="text-4xl md:text-5xl font-bold text-teal-700 mb-4">PrepAI</h1>
                <p className="text-lg md:text-xl text-teal-900 mb-8">
                    Ace your next interview with AI-driven practice and feedback.
                </p>
                <Link
                    to="/interviews"
                    className="bg-teal-600 hover:bg-teal-700 text-white px-6 py-3 rounded-lg font-semibold transition"
                    aria-label="Start Interview"
                >
                    Start Interview
                </Link>

                {/* Video Intro */}
                <div className="mt-10 flex justify-center">
                    <video
                        className="rounded-lg shadow-lg w-full max-w-xl"
                        controls
                        poster="https://via.placeholder.com/640x360?text=PrepAI+Demo"
                    >
                        <source src="https://drive.google.com/file/d/1_7v0fc2c1iq1szdRYXJ-QMXXlC-LDF2_/view?usp=sharing" type="video/mp4" />
                        Your browser does not support the video tag.
                    </video>
                </div>
            </motion.section>

            {/* Features */}
            <section className="max-w-4xl mx-auto py-12 grid gap-8 md:grid-cols-3">
                {features.map((f) => (
                    <motion.div
                        key={f.title}
                        className="bg-white rounded-lg shadow p-6 flex flex-col items-center hover:scale-105 transition-transform duration-300"
                        initial={{ opacity: 0, y: 20 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true }}
                    >
                        {f.icon}
                        <h2 className="mt-4 text-xl font-semibold text-teal-800">{f.title}</h2>
                        <p className="mt-2 text-teal-700 text-center">{f.desc}</p>
                    </motion.div>
                ))}
            </section>

            {/* Testimonials */}
            <motion.section
                className="bg-teal-100 py-12"
                initial={{ opacity: 0 }}
                whileInView={{ opacity: 1 }}
                transition={{ duration: 0.6 }}
                viewport={{ once: true }}
            >
                <h2 className="text-2xl font-bold text-center text-teal-800 mb-8">What users say</h2>
                <div className="max-w-3xl mx-auto grid gap-6 md:grid-cols-2">
                    {testimonials.map((t) => (
                        <motion.div
                            key={t.name}
                            className="bg-white rounded-lg shadow p-6 flex flex-col items-center hover:scale-105 transition-transform duration-300"
                            whileHover={{ scale: 1.05 }}
                        >
                            <FaQuoteLeft className="text-teal-400 text-2xl mb-2" />
                            <p className="text-teal-800 italic mb-4 text-center">&quot;{t.quote}&quot;</p>
                            <span className="font-semibold text-teal-700">- {t.name}</span>
                        </motion.div>
                    ))}
                </div>
            </motion.section>

            {/* FAQ */}
            <section className="max-w-3xl mx-auto py-12 px-4">
                <h2 className="text-2xl font-bold text-teal-800 mb-6 text-center">Frequently Asked Questions</h2>
                <div className="space-y-4">
                    {faqs.map((f) => (
                        <motion.div
                            key={f.q}
                            className="bg-white rounded-lg shadow p-4"
                            initial={{ opacity: 0, y: 10 }}
                            whileInView={{ opacity: 1, y: 0 }}
                            transition={{ delay: 0.1 }}
                            viewport={{ once: true }}
                        >
                            <p className="font-semibold text-teal-700">{f.q}</p>
                            <p className="text-teal-800">{f.a}</p>
                        </motion.div>
                    ))}
                </div>
            </section>

            {/* Newsletter Signup */}
            <motion.section
                className="bg-teal-50 py-12"
                initial={{ opacity: 0 }}
                whileInView={{ opacity: 1 }}
                transition={{ duration: 0.8 }}
                viewport={{ once: true }}
            >
                <div className="max-w-xl mx-auto text-center">
                    <h2 className="text-2xl font-bold text-teal-800 mb-4">Stay Updated</h2>
                    <p className="text-teal-700 mb-6">Get the latest interview tips and platform updates.</p>
                    <form
                        onSubmit={handleSubmit}
                        className="flex flex-col sm:flex-row gap-4 justify-center"
                    >
                        <input
                            type="email"
                            placeholder="Your email"
                            className="px-4 py-2 rounded border border-teal-300 focus:outline-none focus:ring-2 focus:ring-teal-400"
                            required
                            aria-label="Your email address"
                        />
                        <button
                            type="submit"
                            className="bg-teal-600 hover:bg-teal-700 text-white px-6 py-2 rounded font-semibold transition"
                            aria-label="Subscribe"
                        >
                            Subscribe
                        </button>
                    </form>
                </div>
            </motion.section>
        </div>
    );
};

export default Home;
